project:
  type: website
  title: "Introducción a los Procesos Estocásticos IESTA-2025"
  execute-dir: project
  output-dir: docs
  render: 
      - index.qmd
      - practicos_letra/practicos.qmd
      - practicos_letra/practico1-letra.qmd
      - practicos_solucion/practico1-solucion.qmd
      - clases/clase1.qmd
      - calendario.qmd

website:
  title: "461N"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - text: "Calendario"
        file: calendario.html
      - text: "Practicos"
      
        contents:
          - text: "Practico 1"
            file: practicos_letra/practico1-letra.html
      - text: "Soluciones"
        contents:
          - text: "Solución Practico 1"
            file: practicos_solucion/practico1-solucion.html
      - text: "Clases"
        contents:
          - text: "Clase 1"
            file: clases/clase1.html
     
  page-navigation: true


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    embed-resources: true
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

date-format: iso
jupyter: python_venv

