project:
  type: website
  title: "Introducción a los Procesos Estocásticos IESTA-2025"
  execute-dir: project
  output-dir: docs
  render: 
      - index.qmd
      - practicos.qmd
      - practico1-letra.qmd
      - practico1-solucion.qmd

website:
  title: "461N"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - text: "Practicos"
        contents:
          - practico1-letra.qmd
      - text: "Soluciones"
        contents:
          - practico1-solucion.qmd
  page-navigation: true


format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    embed-resources: true
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

date: today
date-format: iso
jupyter: python_venv

